// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEducation(arg1) {
  return window['go']['main']['App']['AddEducation'](arg1);
}

export function AddExperience(arg1) {
  return window['go']['main']['App']['AddExperience'](arg1);
}

export function AddLanguage(arg1) {
  return window['go']['main']['App']['AddLanguage'](arg1);
}

export function AddSkill(arg1) {
  return window['go']['main']['App']['AddSkill'](arg1);
}

export function AddUser(arg1) {
  return window['go']['main']['App']['AddUser'](arg1);
}

export function DeleteAllEducation() {
  return window['go']['main']['App']['DeleteAllEducation']();
}

export function DeleteAllExperience() {
  return window['go']['main']['App']['DeleteAllExperience']();
}

export function DeleteAllLanguage() {
  return window['go']['main']['App']['DeleteAllLanguage']();
}

export function DeleteAllSkill() {
  return window['go']['main']['App']['DeleteAllSkill']();
}

export function DeleteAllUsers() {
  return window['go']['main']['App']['DeleteAllUsers']();
}

export function DeleteEducationByID(arg1) {
  return window['go']['main']['App']['DeleteEducationByID'](arg1);
}

export function DeleteExperienceByID(arg1) {
  return window['go']['main']['App']['DeleteExperienceByID'](arg1);
}

export function DeleteLanguageByID(arg1) {
  return window['go']['main']['App']['DeleteLanguageByID'](arg1);
}

export function DeleteSkillByID(arg1) {
  return window['go']['main']['App']['DeleteSkillByID'](arg1);
}

export function DeleteUserByID(arg1, arg2) {
  return window['go']['main']['App']['DeleteUserByID'](arg1, arg2);
}

export function GetAllEducation(arg1) {
  return window['go']['main']['App']['GetAllEducation'](arg1);
}

export function GetAllExperience(arg1) {
  return window['go']['main']['App']['GetAllExperience'](arg1);
}

export function GetAllLanguages(arg1) {
  return window['go']['main']['App']['GetAllLanguages'](arg1);
}

export function GetAllSkills(arg1) {
  return window['go']['main']['App']['GetAllSkills'](arg1);
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetEducationByID(arg1) {
  return window['go']['main']['App']['GetEducationByID'](arg1);
}

export function GetExperienceByID(arg1) {
  return window['go']['main']['App']['GetExperienceByID'](arg1);
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function GetLanguageByID(arg1) {
  return window['go']['main']['App']['GetLanguageByID'](arg1);
}

export function GetSkillByID(arg1) {
  return window['go']['main']['App']['GetSkillByID'](arg1);
}

export function GetUserByID(arg1) {
  return window['go']['main']['App']['GetUserByID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SendPdfFile(arg1, arg2) {
  return window['go']['main']['App']['SendPdfFile'](arg1, arg2);
}

export function SendPngFile(arg1) {
  return window['go']['main']['App']['SendPngFile'](arg1);
}

export function UpdateEducation(arg1) {
  return window['go']['main']['App']['UpdateEducation'](arg1);
}

export function UpdateExperience(arg1) {
  return window['go']['main']['App']['UpdateExperience'](arg1);
}

export function UpdateLanguage(arg1) {
  return window['go']['main']['App']['UpdateLanguage'](arg1);
}

export function UpdateSkill(arg1) {
  return window['go']['main']['App']['UpdateSkill'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}
